services:
  smtp:
    build:
      context: .
      dockerfile: ./hub/alpine/Dockerfile
    # we push the log out so we can capture it by other service like fail2band
    command: 'tail -f /var/log/postfix.log'
    container_name: postfix
    env_file:
      # for production I switch this to ./docker/.env.prod
      - ./docker/.env.example
    ports:
      - "25:25"
      - "465:465"
      - '587:587'
    volumes:
      - ./data/.users.example:/tmp/passwd
      - ./data/opendkim/domainkey:/etc/opendkim/domainkey
      # this is for dev purpose only, the scripts are being copied by the dockerfile build
      - ./docker/map_ssl.py:/root/map_ssl.py
      - ./docker/setup.sh:/root/setup.sh
